CREATE TABLE AWARD (
    ID INT AUTO_INCREMENT,
    TITEL VARCHAR(255) NOT NULL,
    PRIZE_MONEY DECIMAL(10, 2),
    PRIMARY KEY (ID)
);

CREATE TABLE FILM_AWARD (
    FK_AWARD_ID INT NOT NULL,
    FK_FILM_ID INT(5) UNSIGNED NOT NULL,
    YEAR INT NOT NULL,
    FOREIGN KEY (FK_AWARD_ID) REFERENCES AWARD(ID),
    FOREIGN KEY (FK_FILM_ID) REFERENCES FILM(FILM_ID)
);