SELECT
    COUNT(*),
    C.FIRST_NAME,
    C.LAST_NAME
FROM
    CUSTOMER C
    JOIN RENTAL R
    ON C.CUSTOMER_ID = R.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME
HAVING
    COUNT(*) > 40
ORDER BY
    COUNT(*) DESC;