-- USE DATENBANK;

--SOURCE /DATA/FILE_SHEMA.sql;

--SOURCE /DATA/FILE_DATA.SQL;

--Aufgabe 1

CREATE TABLE AWARD (
    ID INT AUTO_INCREMENT,
    TITEL VARCHAR(255) NOT NULL,
    PRIZE_MONEY VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE FILM_AWARD (
    FK_AWARD_ID INT NOT NULL,
    FILM_ID INT NOT NULL,
    YEAR INT NOT NULL,
    FOREIGN KEY (FK_AWARD_ID) REFERENCES AWARD(ID),
    FOREIGN KEY (FILM_ID) REFERENCES FILM(ID)
);

--Aufgabe 2

ALTER TABLE ACTOR ADD COLUMN BIRTH_YEAR INT(4) NULL;

-- möglich auch YEAR NULL;

--Aufgabe 3

INSERT INTO ACTOR (
    FIRST_NAME,
    LAST_NAME
) VALUES (
    'Hans',
    'Muster'
);

--Aufgabe 4

UPDATE ACTOR
SET
    FIRST_NAME = 'Peter',
    LAST_NAME = 'West'
WHERE
    ACTOR_ID = 115;

--Aufgabe 5

DELETE FROM FILM_ACTOR
WHERE
    ACTOR_ID = 184;

DELETE FROM ACTOR
WHERE
    ACTOR_ID = 184;

--Aufgabe 6

SELECT
    C.FIRST_NAME,
    C.LAST_NAME,
    A.ADDRESS
FROM
    CUSTOMER AS C
    JOIN ADDRESS AS A
    ON C.ADDRESS_ID = A.ADDRESS_ID
WHERE
    C.CUSTOMER_ID = 497;

--Aufgabe 7

SELECT
    RATING,
    COUNT(*) AS ANZAHL
FROM
    FILM
GROUP BY
    RATING
ORDER BY
    RATING;

--Aufgabe 8

SELECT
    C.FIRST_NAME,
    C.LAST_NAME,
    COUNT(R.RENTAL_ID) AS ANZAHL_AUSLEIHEN
FROM
    CUSTOMER AS C
    JOIN RENTAL AS R
    ON C.CUSTOMER_ID = R.CUSTOMER_ID
GROUP BY
    C.FIRST_NAME,
    C.LAST_NAME
HAVING
    ANZAHL_AUSLEIHEN > 40
ORDER BY
    ANZAHL_AUSLEIHEN DESC;